# Generated by Django 5.0.6 on 2024-06-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_cad_usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=255)),
                ("age", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Usuarios",
        ),
    ]
